"""Establish the ECE noise floor and write the report.

Unlike lab_004's runner this never writes into the package directory unless
asked to: `--out` picks the destination, so a smoke run cannot destroy a
committed result.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from labs.lab_007.metrics import bootstrap_ci, expected_calibration_error
from labs.lab_007.synthetic import calibrated, noise_floor, overconfident

HERE = Path(__file__).parent

SIZES: tuple[tuple[int, str], ...] = (
    (50, "lab_004 corpus as it stands"),
    (200, "JBB-Behaviors"),
    (569, "R-Judge"),
    (1000, "deepset/prompt-injections"),
    (4000, ""),
    (10000, "wildguardmix"),
    (20000, ""),
)


def measure(trials: int, seed: int) -> dict:
    floors = [
        {"n": n, "corpus": note, "floor": noise_floor(n, trials=trials, seed=seed)}
        for n, note in SIZES
    ]
    preds, labels = calibrated(4000, seed=seed)
    lo, hi = bootstrap_ci(preds, labels, expected_calibration_error, resamples=500, seed=seed)
    return {
        "meta": {"trials": trials, "seed": seed, "bins": 10},
        "floors": floors,
        "gate": {
            "calibrated_ece": expected_calibration_error(preds, labels),
            "calibrated_ci": [lo, hi],
            "overconfident_ece": expected_calibration_error(
                *overconfident(4000, seed=seed, strength=0.35)
            ),
        },
    }


def render(data: dict) -> str:
    g = data["gate"]
    lines = [
        "# Lab-007 results",
        "",
        f"Seed {data['meta']['seed']}, {data['meta']['trials']} trials per row, "
        f"{data['meta']['bins']} equal-width bins.",
        "",
        "## ECE floor for a perfectly calibrated detector",
        "",
        "| Rows | ECE floor | Corpus at this scale |",
        "| ---: | ---: | --- |",
    ]
    lines += [
        f"| {row['n']:,} | {row['floor']:.4f} | {row['corpus']} |" for row in data["floors"]
    ]
    lines += [
        "",
        "## Instrument gate, 4,000 rows",
        "",
        f"- calibrated detector reads **{g['calibrated_ece']:.4f}** "
        f"(95% CI {g['calibrated_ci'][0]:.4f} to {g['calibrated_ci'][1]:.4f})",
        f"- overconfident detector reads **{g['overconfident_ece']:.4f}**",
        "",
        "Generated by `python -m labs.lab_007.run`.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--trials", type=int, default=30)
    ap.add_argument("--seed", type=int, default=101)
    ap.add_argument("--out", type=Path, default=HERE, help="directory for results")
    args = ap.parse_args()

    data = measure(args.trials, args.seed)
    args.out.mkdir(parents=True, exist_ok=True)
    (args.out / "results.json").write_text(json.dumps(data, indent=1))
    (args.out / "RESULTS.md").write_text(render(data))
    print(render(data))
    print(f"wrote results.json and RESULTS.md to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
